#!/bin/sh

# Ensure we use the appropriate gtkrc-2.0 file
export GTK2_RC_FILES=$HOME/.gtkrc-2.0

# We do not want to rely on crappy mailcap
export MAILCAPS=$HOME/.mailcap

# Make QT automatically scale according to screen DPI
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORMTHEME=qt5ct

# GTK3 apps try to contact org.a11y.Bus. Disable that.
export NO_AT_BRIDGE=1

# Environment variables
unset LC_ALL
[ -e ~/.zshenv ] && . ~/.zshenv
export TERMINAL=vbeterm

# Copy some configuration files
while read source target; do
    for t in $target; do
        mkdir -p $(dirname $HOME/$t)
        ln -nsf ~/.config/i3/dotfiles/$source $HOME/$t
    done
done <<EOF
Xresources   .Xresources
gtkrc-2.0    .gtkrc-2.0
gtk3.css     .config/gtk-3.0/gtk.css
qt5ct.conf   .config/qt5ct/qt5ct.conf
systemd      .config/systemd/user
dunstrc      .config/dunst/dunstrc
picom.conf   .config/picom.conf
polybar.conf .config/polybar/config
firefox.js   .mozilla/firefox/*/user.js
EOF
rm -f ~/.config/gtk-3.0/settings.ini

# Services are started with systemd
systemctl --user import-environment
systemctl --user daemon-reload
exec systemctl --user start --wait xsession.target
